### ISSUE TITLE
Problems, i guess

### ISSUE THREAD

**Issue by Eclipse-04** [3Snake3/multi-lib#3]
![Screenshot_478](https://user-images.githubusercontent.com/43229798/138536068-c3e8ecc3-a691-4c52-9ee6-c523398c360b.png)
i receive this ^
when i use multi.configurable= false
move configurable to hjson file, receive the same thing
*i copy and put the libary file into my own mod

**Comment by 3Snake3** [comment]
@EclipseTheOldOne 
![Screenshot_2021-10-30-00-43-53-398_com.rhmsoft.edit.jpg](https://user-images.githubusercontent.com/83782383/139472899-57de9883-2b87-4fb2-8618-f237b6cef0b4.jpg)You can't change these lines. And you changed it. What for?
That's not working
Configurable must be true, and you mustn't change this.

**Comment by Eclipse-04** [comment]
hmm...sorry

**Comment by Eclipse-04** [comment]
quick question
@3Snake3 ~~heat-lib then~~

**Comment by 3Snake3** [comment]
@EclipseTheOldOne ?

**Comment by Eclipse-04** [comment]
@3Snake3 heat libary used in steam power mod (by youggam)
